(() => {
 const reduced=matchMedia('(prefers-reduced-motion: reduce)'),story=document.querySelector('.module-story'),canvas=document.querySelector('#module-canvas'),ctx=canvas.getContext('2d');
 const clamp=v=>Math.max(0,Math.min(1,v)),smooth=v=>{v=clamp(v);return v*v*(3-2*v)};
 const frames=new Array(73),calls=[...document.querySelectorAll('.component')],timeline=[...document.querySelectorAll('.module-timeline>span')],message=document.querySelector('#module-message');
 const endpoints=[new Image(),new Image()];endpoints[0].src='assets/module-exploded.png';endpoints[1].src='assets/module-closed.png';endpoints.forEach(img=>img.onload=()=>{drawn=-1;schedule()});
 let target=0,current=0,raf=0,loaded=false,drawn=-1;
 const load=i=>new Promise(resolve=>{const img=new Image();img.onload=()=>{frames[i]=img;resolve();drawn=-1;schedule()};img.onerror=resolve;img.src=`assets/module-frames/frame-${String(i+1).padStart(3,'0')}.webp`});
 async function preload(){if(loaded||reduced.matches)return;loaded=true;await Promise.all([load(72),load(0)]);for(let batch=1;batch<72;batch+=8)await Promise.all(Array.from({length:Math.min(8,72-batch)},(_,j)=>load(batch+j)));}
 function amount(p){if(p<.1)return 0;if(p<.36)return smooth((p-.1)/.26);if(p<.69)return 1;if(p<.93)return 1-smooth((p-.69)/.24);return 0}
 function draw(p){const index=Math.round((1-amount(p))*72);let image=frames[index];if(!image){for(let d=1;d<73&&!image;d++)image=frames[index-d]||frames[index+d]}if(!image)return;if(index===drawn)return;drawn=index;const w=canvas.width,h=canvas.height;ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);const render=(img,alpha)=>{if(!img.naturalWidth)return;const scale=Math.min(w/img.width,h/img.height),dw=img.width*scale,dh=img.height*scale;ctx.globalAlpha=alpha;ctx.drawImage(img,(w-dw)/2,(h-dh)/2,dw,dh);ctx.globalAlpha=1};render(image,1);if(index<6)render(endpoints[0],smooth(1-index/6));if(index>66)render(endpoints[1],smooth((index-66)/6));story.classList.add('frames-ready');canvas.dataset.frame=String(index);}
 function resize(){const r=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,1.5);canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);drawn=-1;update()}
 function paint(){raf=0;current+= (target-current)*.16;if(Math.abs(target-current)<.0004)current=target;draw(current);story.style.setProperty('--module-progress',current);const opacity=smooth((current-.32)/.06)*(1-smooth((current-.67)/.05));story.style.setProperty('--callout-opacity',opacity);const focus=Math.min(3,Math.floor(clamp((current-.36)/.3)*4));calls.forEach((el,i)=>el.classList.toggle('is-focus',i===focus));const stage=current<.34?0:current<.75?1:2;timeline.forEach((el,i)=>el.classList.toggle('active',i===stage));message.textContent=stage===0?'One module. A new frame of reference.':stage===1?'Vision. Compute. Connection. Working together.':'Closed enclosure. Open possibilities.';if(current!==target)schedule()}
 function schedule(){if(!raf&&!reduced.matches)raf=requestAnimationFrame(paint)}
 const perception=document.querySelector('.perception-chapter'),vision=document.querySelector('.vision-image'),platform=document.querySelector('.platform-words'),footer=document.querySelector('.contact');
 function update(){if(reduced.matches)return;const rect=story.getBoundingClientRect();target=clamp(-rect.top/Math.max(1,rect.height-innerHeight));if(rect.top<innerHeight*1.8&&rect.bottom>0)preload();schedule();const pr=perception.getBoundingClientRect();perception.style.setProperty('--scene-travel',clamp((innerHeight-pr.top)/(innerHeight+pr.height)));vision.style.setProperty('--image-reveal',smooth((innerHeight-vision.getBoundingClientRect().top)/(innerHeight*.65)));const progress=clamp((innerHeight-platform.getBoundingClientRect().top)/(innerHeight*.7));[...platform.children].forEach((el,i)=>el.classList.toggle('lit',progress>(i*.18+.08)));document.querySelectorAll('.roadmap li').forEach(el=>{const r=el.getBoundingClientRect();el.classList.toggle('reading',r.top<innerHeight*.6&&r.bottom>innerHeight*.4)});footer.style.setProperty('--footer-reveal',clamp((innerHeight-footer.getBoundingClientRect().top)/innerHeight));}
 let scrollQueued=false;addEventListener('scroll',()=>{if(!scrollQueued){scrollQueued=true;requestAnimationFrame(()=>{scrollQueued=false;update()})}},{passive:true});addEventListener('resize',resize,{passive:true});
 function motionMode(){if(reduced.matches){cancelAnimationFrame(raf);raf=0;story.classList.remove('frames-ready');story.classList.add('static-module');document.querySelector('.module-fallback').src='assets/module-exploded.png';document.querySelector('.module-fallback').alt='Exploded concept view of the module enclosure, compute board, cameras and internal connections';message.textContent='Vision, compute, and platform interfaces in one module.'}else{story.classList.remove('static-module');resize()}}
 reduced.addEventListener('change',motionMode);motionMode();
})();
